# -*- coding: utf-8 -*-
"""WebScrapper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uIayc1lsUv0Ac_sWhKEywRb7L43Hamy3
"""

!pip install requests_html

!pip install pygooglenews --upgrade

from pygooglenews import GoogleNews

from requests_html import HTMLSession

def get_titles(search):
  stories =[]
  gn = GoogleNews(country='IN')
  search = gn.search(search)
  newsitem = search['entries']
  for item in newsitem:
    story ={
        'title' : item.title,
        'link'  : item.link,
    }
    stories.append(story)
  return stories

get_titles('Maharashtra')